server:
  port: ${SERVER_PORT:8091}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/homestay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
    username: ${SPRING_DATASOURCE_USERNAME:homestay}
    password: ${SPRING_DATASOURCE_PASSWORD:homestay123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Redis配置
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      indent_output: false
      fail_on_empty_beans: false

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.nop.NopImpl

# 日志配置
logging:
  level:
    com.homestay: ${LOG_LEVEL:INFO}
    org.springframework.web: WARN
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/homestay.log
    max-size: 100MB
    max-history: 30

# Sa-Token配置
sa-token:
  token-name: satoken
  timeout: 86400
  activity-timeout: 86400
  is-auto-renew: true
  auto-renew-count: 100
  token-style: uuid
  is-log: false
  is-concurrent: true
  is-share: true
  max-login-count: 3
  is-v: false

# 文件配置
file:
  ip: ${FILE_IP:localhost}

# AI服务配置
chatAssist:
  authorization: ${CHAT_ASSIST_AUTH:Bearer app-oaUwvb7k2zbC8Bi03EO977nN}
  url: ${CHAT_ASSIST_URL:http://4295a4ce.r28.cpolar.top/v1}

ai:
  api:
    url: ${AI_API_URL:http://4295a4ce.r28.cpolar.top/v1/chat/completions}
    key: ${AI_API_KEY:app-oaUwvb7k2zbC8Bi03EO977nN}
  backup:
    enabled: true
    service: local

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: ${ENABLE_MONITORING:true}
